name: Booking Service CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create .env file
      run: |
        cat > .env << EOF
        POSTGRES_HOST=localhost
        POSTGRES_PORT=5432
        POSTGRES_DB=postgres
        POSTGRES_USER=postgres
        POSTGRES_PASSWORD=postgres
        APP_PORT=3000
        EOF
        
    - name: Build project
      run: npm run build
      
    - name: Run migrations
      run: npx knex migrate:latest --knexfile ./dist/src/config/db/knexfile.js
    
    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test
    
    - name: Run linting
      run: npm run lint